untabify
Expand all tabs to spaces (with two exceptions in the i and ui scripts,
where the literal tabs are needed).

My main reason for switching is that tabs are converted to spaces when
copy-pasting between terminal emulator windows, and it's a hassle to
convert the spaces back into tabs.

The decision to indent with 2 spaces rather than 4 spaces is something
of an experiment.

diff --git a/dot_local/bin/executable_et b/dot_local/bin/executable_et
--- a/dot_local/bin/executable_et
+++ b/dot_local/bin/executable_et
@@ -3,75 +3,75 @@
 set -u
 
 usage() {
-	echo "usage: $0 [-t tab_stop] [file ...]" 1>&$1
-	echo "Expand tabs to spaces assuming tab stops every tab_stop (default 4) columns." 1>&$1
-	echo "If files are specified, expands tabs in them; otherwise reads from stdin and" 1>&$1
-	echo "writes to stdout." 1>&$1
-	exit $(($1 - 1))
+  echo "usage: $0 [-t tab_stop] [file ...]" 1>&$1
+  echo "Expand tabs to spaces assuming tab stops every tab_stop (default 4) columns." 1>&$1
+  echo "If files are specified, expands tabs in them; otherwise reads from stdin and" 1>&$1
+  echo "writes to stdout." 1>&$1
+  exit $(($1 - 1))
 }
 
 tabw=4
 while getopts t:h name; do
-	case $name in
-	t) tabw=$OPTARG;;
-	h) usage 1;;
-	?) usage 2;;
-	esac
+  case $name in
+  t) tabw=$OPTARG;;
+  h) usage 1;;
+  ?) usage 2;;
+  esac
 done
 shift $(($OPTIND - 1))
 
 [ $# -eq 0 ] && exec expand -t$tabw
 
 cp_attr() {
-	src="$1"
-	dst="$2"
-	if [ "$(uname)" = "Linux" ]; then
-		# copy attributes only
-		# GNU coreutils cp(1) extension
-		cp -a --attributes-only "$src" "$dst"
-	else
-		# copies attributes _and_ data
-		cp -a "$src" "$dst"
-	fi
+  src="$1"
+  dst="$2"
+  if [ "$(uname)" = "Linux" ]; then
+    # copy attributes only
+    # GNU coreutils cp(1) extension
+    cp -a --attributes-only "$src" "$dst"
+  else
+    # copies attributes _and_ data
+    cp -a "$src" "$dst"
+  fi
 }
 
 for f in "$@"; do
-	# create a temporary file
-	tmpf="$(mktemp)"
-	if [ $? -ne 0 ]; then
-		ev=$?
-		echo "$0: error creating temporary file, stopping" 1>&2
-		exit $ev
-	fi
+  # create a temporary file
+  tmpf="$(mktemp)"
+  if [ $? -ne 0 ]; then
+    ev=$?
+    echo "$0: error creating temporary file, stopping" 1>&2
+    exit $ev
+  fi
 
-	# ensure the temporary file has the same attributes as the file being
-	# processed, so that no attributes are changed when replace the file
-	# being processed with the original file
-	cp_attr "$f" "$tmpf"
-	if [ $? -ne 0 ]; then
-		ev=$?
-		echo "$0: error updating attributes on $tmpf, stopping" 1>&2
-		rm "$tmpf"
-		exit $ev
-	fi
+  # ensure the temporary file has the same attributes as the file being
+  # processed, so that no attributes are changed when replace the file
+  # being processed with the original file
+  cp_attr "$f" "$tmpf"
+  if [ $? -ne 0 ]; then
+    ev=$?
+    echo "$0: error updating attributes on $tmpf, stopping" 1>&2
+    rm "$tmpf"
+    exit $ev
+  fi
 
-	expand -t$tabw <"$f" >"$tmpf"
-	if [ $? -ne 0 ]; then
-		ev=$?
-		echo "$0: error expanding $f into $tmpf, stopping" 1>&2
-		rm "$tmpf"
-		exit $ev
-	fi
+  expand -t$tabw <"$f" >"$tmpf"
+  if [ $? -ne 0 ]; then
+    ev=$?
+    echo "$0: error expanding $f into $tmpf, stopping" 1>&2
+    rm "$tmpf"
+    exit $ev
+  fi
 
-	# skip rewriting the file if nothing changed
-	if cmp "$tmpf" "$f" >/dev/null 2>&1; then
-		rm "$tmpf"
-	else
-		mv "$tmpf" "$f"
-		if [ $? -ne 0 ]; then
-			ev=$?
-			echo "$0: error moving $tmpf to $f, stopping" 1>&2
-			exit $ev
-		fi
-	fi
+  # skip rewriting the file if nothing changed
+  if cmp "$tmpf" "$f" >/dev/null 2>&1; then
+    rm "$tmpf"
+  else
+    mv "$tmpf" "$f"
+    if [ $? -ne 0 ]; then
+      ev=$?
+      echo "$0: error moving $tmpf to $f, stopping" 1>&2
+      exit $ev
+    fi
+  fi
 done
diff --git a/dot_local/bin/executable_zfs-health b/dot_local/bin/executable_zfs-health
--- a/dot_local/bin/executable_zfs-health
+++ b/dot_local/bin/executable_zfs-health
@@ -3,26 +3,26 @@
 set -eu
 
 if [ $# -ne 0 ]; then
-	echo "usage: $0" 1>&2
-	echo 'Health check-up for systems using ZFS.' 1>&2
-	exit 1
+  echo "usage: $0" 1>&2
+  echo 'Health check-up for systems using ZFS.' 1>&2
+  exit 1
 fi
 
 # Ensure this system has ZFS and Sanoid.
 bin='zfs zpool sanoid'
 for b in $bin; do
-	if ! command -v $b >/dev/null 2>&1; then
-		echo "error: $b executable not found in PATH" 1>&2
-		exit 1
-	fi
+  if ! command -v $b >/dev/null 2>&1; then
+    echo "error: $b executable not found in PATH" 1>&2
+    exit 1
+  fi
 done
 
 # On NixOS, sanoid.conf is kept in /nix/store and Sanoid doesn't know where to
 # find it, so we need to tell Sanoid its location.
 configarg=''
 if [ -d /etc/nixos ]; then
-	configdir="$(systemctl cat sanoid | rg 'sanoid\.conf' | awk '{print $4}' | tr -d "'")"
-	[ -d "$configdir" ] && configarg="--configdir=${configdir}"
+  configdir="$(systemctl cat sanoid | rg 'sanoid\.conf' | awk '{print $4}' | tr -d "'")"
+  [ -d "$configdir" ] && configarg="--configdir=${configdir}"
 fi
 
 # To avoid interfering with the sanoid system service, use a separate temporary
@@ -33,27 +33,27 @@ cachedir="$tmpd/cache"
 rundir="$tmpd/run"
 
 z() {
-	echo '== SYSTEM UPTIME =='
-	who -b | sed 's/^ *//'
-	uptime | sed 's/^ *//'
+  echo '== SYSTEM UPTIME =='
+  who -b | sed 's/^ *//'
+  uptime | sed 's/^ *//'
 
-	echo '== ZPOOL STATUS =='
-	zpool status
+  echo '== ZPOOL STATUS =='
+  zpool status
 
-	echo '== SANOID MONITOR: HEALTH =='
-	sanoid --monitor-health $configarg --cache-dir="$cachedir" --run-dir="$rundir"
+  echo '== SANOID MONITOR: HEALTH =='
+  sanoid --monitor-health $configarg --cache-dir="$cachedir" --run-dir="$rundir"
 
-	echo '== SANOID MONITOR: SNAPSHOTS =='
-	sanoid --monitor-snapshots $configarg --cache-dir="$cachedir" --run-dir="$rundir"
+  echo '== SANOID MONITOR: SNAPSHOTS =='
+  sanoid --monitor-snapshots $configarg --cache-dir="$cachedir" --run-dir="$rundir"
 
-	echo '== SANOID MONITOR: CAPACITY =='
-	sanoid --monitor-capacity $configarg --cache-dir="$cachedir" --run-dir="$rundir"
+  echo '== SANOID MONITOR: CAPACITY =='
+  sanoid --monitor-capacity $configarg --cache-dir="$cachedir" --run-dir="$rundir"
 
-	echo '== ZFS LIST =='
-	zfs list
+  echo '== ZFS LIST =='
+  zfs list
 
-	echo '== ZFS SNAPSHOTS =='
-	zfs list -t snapshot
+  echo '== ZFS SNAPSHOTS =='
+  zfs list -t snapshot
 }
 
 z | less
@@ -64,15 +64,15 @@ peb=''
 command -v sudo >/dev/null 2>&1 && peb='sudo'
 command -v doas >/dev/null 2>&1 && peb='doas'
 if [ ! -z "$peb" ]; then
-	if [ "$(uname)" = "Linux" ]; then
-		rf="/proc/sys/kernel/dmesg_restrict"
-		if [ -r "$rf" ] && [ "$(cat "$rf")" = "1" ]; then
-			pe="$peb"
-		fi
-	elif [ "$(uname)" = "FreeBSD" ]; then
-		un="$(sysctl security.bsd.unprivileged_read_msgbuf | awk '{print $2}')"
-		[ "$un" = "0" ] && pe="$peb"
-	fi
+  if [ "$(uname)" = "Linux" ]; then
+    rf="/proc/sys/kernel/dmesg_restrict"
+    if [ -r "$rf" ] && [ "$(cat "$rf")" = "1" ]; then
+      pe="$peb"
+    fi
+  elif [ "$(uname)" = "FreeBSD" ]; then
+    un="$(sysctl security.bsd.unprivileged_read_msgbuf | awk '{print $2}')"
+    [ "$un" = "0" ] && pe="$peb"
+  fi
 fi
 
 # Run dmesg to ensure the kernel hasn't panicked.
diff --git a/dot_shrc.tmpl b/dot_shrc.tmpl
--- a/dot_shrc.tmpl
+++ b/dot_shrc.tmpl
@@ -2,7 +2,7 @@
 # Can be sourced from .zshrc, .bashrc, .kshrc, etc.
 
 iscmd() {
-	command -v "$1" >/dev/null 2>&1
+  command -v "$1" >/dev/null 2>&1
 }
 
 alias df='df -h'
@@ -32,10 +32,10 @@ alias chgrp='chgrp --preserve-root'
 
 # Add directory to PATH if it exists and isn't already in PATH.
 addtopath() {
-	[ ! -d $1 ] && return
-	echo "$PATH" | grep ":$1$" >/dev/null && return
-	echo "$PATH" | grep ":$1:" >/dev/null && return
-	export PATH=$PATH:$1
+  [ ! -d $1 ] && return
+  echo "$PATH" | grep ":$1$" >/dev/null && return
+  echo "$PATH" | grep ":$1:" >/dev/null && return
+  export PATH=$PATH:$1
 }
 
 addtopath $HOME/bin
@@ -44,9 +44,9 @@ addtopath $HOME/go/bin
 addtopath $HOME/.cargo/bin
 
 if [ -d /usr/local/plan9 ]; then
-	export PLAN9=/usr/local/plan9
+  export PLAN9=/usr/local/plan9
 elif [ -d $HOME/plan9 ]; then
-	export PLAN9=$HOME/plan9
+  export PLAN9=$HOME/plan9
 fi
 [ ! -z "$PLAN9" ] && addtopath $PLAN9/bin
 
@@ -55,67 +55,67 @@ fi
 {{- if or (eq .chezmoi.os "darwin") (eq .chezmoi.os "freebsd") (eq .chezmoi.os "openbsd") }}
 vis_exe='vise'
 if iscmd $vis_exe; then
-	alias visu='/usr/bin/vis'
-	alias vis='vise'
+  alias visu='/usr/bin/vis'
+  alias vis='vise'
 fi
 {{- else }}
 vis_exe='vis'
 {{- end }}
 
 if iscmd $vis_exe; then
-	export EDITOR=$vis_exe
-	export VISUAL=$vis_exe
+  export EDITOR=$vis_exe
+  export VISUAL=$vis_exe
 fi
 
 # Short-hand for the default editor
 [ -n "$VISUAL" ] && alias e="$VISUAL"
 
 if iscmd fzf; then
-	fzp() {
-		if [ $# -lt 1 ]; then
-			echo "fzp: must specify a program name" 1>&2
-			return 1
-		fi
-		program="$1"
-		shift
-		"$program" "$@" $(fzf -m)
-	}
+  fzp() {
+    if [ $# -lt 1 ]; then
+      echo "fzp: must specify a program name" 1>&2
+      return 1
+    fi
+    program="$1"
+    shift
+    "$program" "$@" $(fzf -m)
+  }
 
-	fze() {
-		if [ -z "$VISUAL" ]; then
-			echo "fze: cannot open editor when VISUAL is unset"
-			return 1
-		fi
-		fzp "$VISUAL" "$@"
-	}
+  fze() {
+    if [ -z "$VISUAL" ]; then
+      echo "fze: cannot open editor when VISUAL is unset"
+      return 1
+    fi
+    fzp "$VISUAL" "$@"
+  }
 fi
 
 mkcd() {
-	if [ $# -eq 0 ]; then
-		echo "$0: missing operand" 1>&2
-		echo "usage: $0 directory" 1>&2
-		echo "mkdir and chdir into the given directory." 1>&2
-		return 1
-	fi
-	mkdir -p "$1"
-	cd "$1"
+  if [ $# -eq 0 ]; then
+    echo "$0: missing operand" 1>&2
+    echo "usage: $0 directory" 1>&2
+    echo "mkdir and chdir into the given directory." 1>&2
+    return 1
+  fi
+  mkdir -p "$1"
+  cd "$1"
 }
 
 upcd() {
-	dir=""
-	for i in $(seq 1 $1); do
-		dir="../$dir"
-	done
-	[ -z "$dir" ] && dir="$PWD"
-	cd "$dir"
+  dir=""
+  for i in $(seq 1 $1); do
+    dir="../$dir"
+  done
+  [ -z "$dir" ] && dir="$PWD"
+  cd "$dir"
 }
 
 lk() {
-	if ! iscmd walk; then
-		echo "lk: walk must be installed" 1>&2
-		return 1
-	fi
-	cd "$(walk "$@")"
+  if ! iscmd walk; then
+    echo "lk: walk must be installed" 1>&2
+    return 1
+  fi
+  cd "$(walk "$@")"
 }
 
 # Debian/Ubuntu renamed fd to fdfind due to a naming conflict.
@@ -123,29 +123,29 @@ iscmd fdfind && ! iscmd fd && alias fd='fdfind'
 
 # Consistent name for Sublime Merge
 if ! iscmd subm; then
-	if iscmd sublime_merge; then
-		alias subm='sublime_merge'
-	elif iscmd subl-merge; then
-		alias subm='subl-merge'
-	elif iscmd smerge; then
-		alias subm='smerge'
-	elif iscmd flatpak; then
-		if flatpak info com.sublimemerge.App >/dev/null 2>&1; then
-			alias subm='flatpak run com.sublimemerge.App'
-		fi
-	fi
+  if iscmd sublime_merge; then
+    alias subm='sublime_merge'
+  elif iscmd subl-merge; then
+    alias subm='subl-merge'
+  elif iscmd smerge; then
+    alias subm='smerge'
+  elif iscmd flatpak; then
+    if flatpak info com.sublimemerge.App >/dev/null 2>&1; then
+      alias subm='flatpak run com.sublimemerge.App'
+    fi
+  fi
 fi
 # Consistent name for Sublime Text
 if ! iscmd subl; then
-	if iscmd sublime_text; then
-		alias subl='sublime_text'
-	elif iscmd subl-text; then
-		alias subl='subl-text'
-	elif iscmd subl4; then
-		alias subl='subl4'
-	elif iscmd flatpak; then
-		if flatpak info com.sublimehq.SublimeText >/dev/null 2>&1; then
-			alias subl='flatpak run com.sublimehq.SublimeText'
-		fi
-	fi
+  if iscmd sublime_text; then
+    alias subl='sublime_text'
+  elif iscmd subl-text; then
+    alias subl='subl-text'
+  elif iscmd subl4; then
+    alias subl='subl4'
+  elif iscmd flatpak; then
+    if flatpak info com.sublimehq.SublimeText >/dev/null 2>&1; then
+      alias subl='flatpak run com.sublimehq.SublimeText'
+    fi
+  fi
 fi
